-
  branches:
    only:
      - master

  build_script:
    - ps: .\build.cmd PublishNuget
  test: off
  version: 1.0.0.{build}
  artifacts:
    - path: bin\*.nupkg
      name: NuGet

# "fall back" configuration for all other branches
# no "branches" section defined
# do not deploy at all
-
  build_script:
    - ps: .\build.cmd
  test: off
  version: 1.0.0.{build}
  artifacts:
    - path: bin\*.nupkg
      name: NuGet
