-
  branches:
    only:
      - master

  skip_non_tags: true
  build_script:
    - ps: .\build.cmd PublishNuget
  test: off
  artifacts:
    - path: bin\*.nupkg
      name: NuGet

# "fall back" configuration for all other branches
# no "branches" section defined
-
  build_script:
    - ps: .\build.cmd
  test: off
  artifacts:
    - path: bin\*.nupkg
      name: NuGet
